project:
  type: book
  output-dir: _book

book:
  title: "Quarto & Github Actions"
  author: "Jeremiah Lewis"
  date: "2022-04-13"
  chapters:
    - index.qmd
    - julia-supporting-material.qmd
    - r-supporting-material.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
