on:
  push:
    branches: main
    paths:
      - quarto-actions/
  pull_request:
    branches: main
    paths:
      - quarto-actions/
  workflow_dispatch:

name: Render and deploy Book

env:
  QUARTO_TAG: jeremiahpslewis/quarto:v1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .devcontainer/
          load: true
          tags: ${{ env.QUARTO_TAG }}
      -
        name: Test
        run: |
          docker run --rm ${{ env.QUARTO_TAG }}    
      - 
        name: Render book to all formats
        run: |
          quarto render quarto-actions
      - 
        name: Deploy 🚀
        # only deploy when push to main
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # The branch the action should deploy to.
          branch: gh-pages
          # The folder the action should deploy. Adapt if you changed in Quarto config
          folder: quarto-actions/_book
