on:
  push:
    branches: main
    paths:
      - quarto-actions/
      - .github/workflows/quarto.yml
  pull_request:
    branches: main
    paths:
      - quarto-actions/
      - .github/workflows/quarto.yml
  registry_package:
    types: [published, updated]
  workflow_dispatch:

name: Render and deploy Book

jobs:
  docker:
    runs-on: ubuntu-latest
    container: ghcr.io/jeremiahpslewis/quarto-reproducible-gh-actions:main
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - 
        name: Render book to all formats
        run: |
          quarto render quarto-actions -P img_format:png --to pdf
          mv quarto-actions/_book/quarto-and-github-actions.pdf .
          quarto render quarto-actions -P img_format:svg --to html
          mv quarto-and-github-actions.pdf quarto-actions/_book/
      - 
        name: Deploy 🚀
        # only deploy when push to main
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # The branch the action should deploy to.
          branch: gh-pages
          # The folder the action should deploy. Adapt if you changed in Quarto config
          folder: quarto-actions/_book
